### ISSUE TITLE
Allow Aeson 1.3

### ISSUE THREAD

**Issue by jpvillaisaza** [MercuryTechnologies/slack-web#59]
See fpco/stackage#3337.

**Comment by emmanueltouzery** [comment]
i didn't make a PR yet because anyway our servant dependency prevents it for now. They merged my PR to allow it but we'll have to wait for the release https://github.com/haskell-servant/servant/pull/919

We could test against their git master version and if we build ourselves against the latest aeson, we could release with our constraint relaxed.. but i didn't bother for now.

**Comment by jpvillaisaza** [comment]
@emmanueltouzery Sounds great (to not bother with it for now), thanks!
