### ISSUE TITLE
[RFC] Don't force "ReaderT Pattern"

### ISSUE THREAD

**Issue by igrep** [MercuryTechnologies/slack-web#90]
# Problem

Current API functions in slack-web are typed as following for example:

```hs
authTest :: (MonadReader env m, HasManager env, HasToken env, MonadIO m) => m (Response TestRsp) 
```

IMO this is confusing for people unfamiliar with the "ReaderT Pattern" (e.g. Newbies who just want to try Slack Web API in Haskell). Helping the users adopt the "ReaderT Pattern" is NOT slack-web's responsibility because it isn't directly related to the "ReaderT Pattern". In addition, the simplified versions (for example below) and the original versions are easily converted mutually:

```hs
authTest ::  SlackConfig -> IO (Response TestRsp)
-- Or
authTest :: Manager -> SlackConfigToken -> IO (Response TestRsp)
type SlackConfigToken = Text
```

# Suggested Changes

- Change the type of the API functions into `SlackConfig -> IO (Response a)`
- Leave the current version as a separate module `Web.Slack.ReaderT` for convenience and compatibility.

**Comment by jpvillaisaza** [comment]
@igrep I'm not sure whether using the pattern necessarily means it's the responsibility of the library to explain it, but it looks like there's not much content there (the config or other required values) and the non-ReaderT pattern version might be better/simpler, so this sounds good to me. 👍 

Perhaps keep it with `MonadIO` if that makes sense. And perhaps a different name for the separate module (other than `ReaderT`, but I can't think of one at the moment, so that's fine as well).
