### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by jpvillaisaza** [MercuryTechnologies/slack-web#94]
CI is out of date. See https://github.com/jpvillaisaza/slack-web/pull/93#issuecomment-1233516085 for a recommendation to use `haskell-ci` or switch to GitHub Actions.

**Comment by lf-** [comment]
I'm working on this right now, as well as nixifying slack-web at Mercury. I also have some further plans with it.

**Comment by jpvillaisaza** [comment]
@lf- Sounds good, thank you!

**Comment by lf-** [comment]
I just double checked: @MercuryTechnologies can take over maintainership of the library :)

Due to [vagaries of GitHub design](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#repository-transfers-and-organizations), it would need to be transferred to an individual account who is a member of the organization. I would be happy to do this process with my account `@LF-`, and @avieth could as well. 

One of the plans we have is to open source parts of our internal slack integration such as webhooks and a message builder into slack-web.

**Comment by jpvillaisaza** [comment]
Do you mean it would need to be transferred first to your account (or the account of someone from Mercury) and then from that account to the Mercury organization?

**Comment by lf-** [comment]
> Do you mean it would need to be transferred first to your account (or the account of someone from Mercury) and then from that account to the Mercury organization?

That's correct, since transferring to an organization requires repository creation permission according to the docs I linked.

**Comment by jpvillaisaza** [comment]
Okay, sounds good! I opened #96 for things related to transferring the library.
